### PR TITLE
Fix docker compose example for 0.1.0-alpha.2

### PR DESCRIPTION
**Pull request by farrajota**
This PR fixes the environment variable names in docker-compose.yml example setup for the v0.1.0-alpha.2.

### CODE REVIEW

**Comment by antekresic** [comment]
Thank you for the contribution! 

Would you mind squashing the commits? We can merge this immediately after that.

**Comment by farrajota** [comment]
Since the latest docker image of timescale is working with this setup, would you rather have the current image `timescale/pg_prometheus:latest-pg11` replaced by  `timescale/timescaledb:latest-pg12` ?

**Comment by antekresic** [comment]
@farrajota that sounds good! We definitely don't tepend on pg_prometheus for the connector.

**Comment by antekresic** [comment]
Looking good! Thanks again @farrajota

**Pull request merged**
